# This helm values file defines app-based settings
# Charts use those values, so this file **MUST** be included in all chart releases

app:                                                    # app global settings
  name: "the-broker"                                    # Override for custom app name
  ingress:                                              # ingress related settings
    entries:
      owners: owners-api                                # ingress entry for owners api
      apartment: apartment-api                          # ingress entry for apartment api
      identity: identity                                # ingress entry for identity api
      mvc: webmvc                                       # ingress entry for web mvc
      signalrhub: signalrhub
      webclientapigw: webclientapigw                    # ingress entry for web client api gateway
      webclientaggapigw: webclientaggapigw              # ingress entry for web client Agg gateway     
      webclientagg: webclientagg                        # ingress entry for web client Agg
  svc:
      owners: owners-api                                # service name for owners api
      apartment: apartment-api                          # service name for apartment api
      identity: identity-api                            # service name for identity api
      mvc: webmvc                                       # service name for web mvc
      signalrhub: signalrhub                            # service name for signalrhub
      webclientapigw: webclientapigw                    # service name for web client api gateway
      webclientaggapigw: webclientaggapigw              # service name for web client Agg gateway
      webclientagg: webclientagg                        # service name for web client Agg

