version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  redis:
    image: redis:alpine

  identity.api:
    image: ${REGISTRY:-broker}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    

  webmvc:
    image: ${REGISTRY:-broker}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile
