version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  cache:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: ${REGISTRY:-broker}/identity-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile 

  apartment-api:
    image: ${REGISTRY:-broker}/apartment-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Apartment/Apartment.API/Dockerfile 
    depends_on:
      - rabbitmq

  owners-api:
    image: ${REGISTRY:-broker}/owners-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Owners/Owners.API/Dockerfile      

  signalrhub:
    image: ${REGISTRY:-broker}/signalrhub:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/SignalR/SignalrHub/Dockerfile
    depends_on:      
      - identity-api
      - rabbitmq
      - apartment-api

  webmvc:
    image: ${REGISTRY:-broker}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile
    depends_on:      
      - identity-api
      - cache

  webclientapigw:
    image: envoyproxy/envoy:v1.11.1

  webclientaggapigw:
    image: envoyproxy/envoy:v1.11.1

  webclientagg:
    image: ${REGISTRY:-broker}/webclientagg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff/WebClientAgg/Dockerfile
    depends_on:
      - owners-api
      - apartment-api
      - identity-api
