# Default values for owners.api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
clusterName: broker-aks
pathBase: /owners.api

image:
  repository: broker/owners.api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  grpcPort: 81

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ConnectionString
      key: owners__ConnectionString
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: UseLoadTest
      key: all__EnableLoadTest
    - name: IdentityUrl
      key: urls__IdentityUrl
    - name: UseCustomizationData
      key: all__UseCustomization
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: PORT
      value: "80"
    - name: GRPC_PORT
      value: "81"
probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80
