replicaCount: 1
clusterName: broker-aks
pathBase: /identity

image:
  repository: broker/identity-api
  tag: linux-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - identity.local
  tls: []

resources:
  requests:
    memory: "250Mi"
    cpu: "500m"

nodeSelector: {}

tolerations: []

affinity: {}

env:
  urls:
  configmap:
    - name: ConnectionString
      key: identity__ConnectionString
    - name: DPConnectionString
      key: identity__keystore
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: MvcClient
      key: mvc_e
    - name: OwnerApiClient
      key: owner_e
    - name: ApartmentApiClient
      key: apartment_e
    - name: WebClientAggClient
      key: WebClientAgg_e
    - name: UseCustomizationData
      key: all__UseCustomization
    - name: EnableDevspaces
      key: enableDevspaces
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80