apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: webmvc
  name: webmvc-loopback
  namespace: default
spec:
  rules:
  - http: 
      paths:
      - backend:
          serviceName: webmvc
          servicePort: http
        path: /webmvc
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: identity-api
  name: identity-api-loopback
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: identity-api
          servicePort: http
        path: /identity