apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.svc.webclientaggapigw }}
  labels:
    app: {{ template "webclientaggapigw.name" . }}
    chart: {{ template "webclientaggapigw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin     
  selector:
    app: {{ template "webclientaggapigw.name" . }}
    release: {{ .Release.Name }}